### ISSUE TITLE
Fails on VSCode 1.21.0 / Windows 10

### ISSUE THREAD

**Issue by whitetigle** [ionide/ionide-vscode-mechanic#15]
Hi guys!
Just installed the plugin and got a failure with ouput:
```
 An assembly specified in the application dependencies manifest (mech.deps.json) was not found:
    package: 'FSharp.Compiler.Service', version: '17.0.1'
    path: 'lib/netstandard1.6/FSharp.Compiler.Service.dll'
```

What other information do you need?

**Comment by forki** [comment]
looks like we need to call .net publish

**Comment by MangelMaxime** [comment]
Ok, so we should add a new target on Mechanic repo.
Perhaps we should profit of this to call `publish` in `Release` configuration ?

**Comment by forki** [comment]
I did that manually as quickfix @whitetigle can you please try 0.0.9?

**Comment by whitetigle** [comment]
sure 👍

**Comment by landy** [comment]
It works now

**Comment by whitetigle** [comment]
ok it works for me 👍

**Comment by whitetigle** [comment]
Great job guys! 👏
