### ISSUE TITLE
Mechanic shows StackOverflowException

### ISSUE THREAD

**Issue by tforkmann** [ionide/ionide-vscode-mechanic#22]
Mechanic now shows this error:

![image](https://user-images.githubusercontent.com/4168951/37649687-d4d61af6-2c32-11e8-97fc-a1b50434bb15.png)

**Comment by jindraivanek** [comment]
@tforkmann can you share project?

**Comment by tforkmann** [comment]
Sorry for the late response. I will clean it up and then share it.

**Comment by tforkmann** [comment]
Got it fixed somehow...closing it now.
