### ISSUE TITLE
Show in the status bar that Mechanic is running ?

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-mechanic#5]
When Ionide is loading F# project, it display a little text and animation in the status bar. We probably should do that when running Mechanic too so users don't have the feeling it's doing nothing.

**Comment by forki** [comment]
currently mechanic opens in new window for me.
/cc @Krzysztof-Cieslak

**Comment by MangelMaxime** [comment]
@forki It's starting a new terminal ?

Could you please do a gif because I don't have this behavior ?

**Comment by forki** [comment]
I'm on windows. maybe that's why?

**Comment by MangelMaxime** [comment]
I think it's the reason but would be better to have the same behavior across the OS :)

**Comment by Krzysztof-Cieslak** [comment]
Mechanic is not opening new window for me, tho I'm on Linux at the moment. Also, I think it shouldn't open any new window. 

To get this text + animation we use Progress API - `window.withProgress` function. Example: https://github.com/ionide/ionide-vscode-fsharp/blob/f64c58901851ed7b2d88f3c485b2d3082011b3c1/src/fsharp.fs#L33-L35

**Comment by forki** [comment]
![mechanic](https://user-images.githubusercontent.com/57396/37344894-eddaf4b6-26cb-11e8-9d72-8c1004ae3007.gif)

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/37345109-72eefee0-26cc-11e8-9430-a76fd58c0302.png)

seems to fix it - should I remove that flag?

**Comment by MangelMaxime** [comment]
I don't like removing this flag because then it's opening a new termial in VSCode.

I have an extensio doing that and it's really annoying because it's mask my active terminal. I propose to remove the flag on windows only ?

**Comment by forki** [comment]
ok. can you please do that?

**Comment by MangelMaxime** [comment]
Sure will do, I am trying to fix something else. Loading the project using Ionide seems broken for me, I am trying to understand.

**Comment by MangelMaxime** [comment]
Finally, removing `shell` on OS X don't open the new terminal windows so I just remove the option all the time.
