### ISSUE TITLE
Filter the list of projects in Mechanic.fs to the ones that contain the currently opended file

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-mechanic#9]
/cc @Krzysztof-Cieslak

**Comment by forki** [comment]
we also need to deduplicate

![image](https://user-images.githubusercontent.com/57396/37349574-102778b8-26d7-11e8-8199-55cd69d26a87.png)

/cc @MangelMaxime

**Comment by MangelMaxime** [comment]
Yes, and to do that we need to change the `state` structure 

https://github.com/ionide/ionide-vscode-mechanic/pull/10#discussion_r174152717

**Comment by Krzysztof-Cieslak** [comment]
Getting project to which file belongs should be fairly simple - `Project` object contains list of files, getting current path is `window.activeTextEditor.document.filename`

**Comment by MangelMaxime** [comment]
I already have this implemented, I just don't know which data structure to use for state ? Is it `Dictionnary` ? @Krzysztof-Cieslak

**Comment by Krzysztof-Cieslak** [comment]
Yes, `Dictionary` sounds good, I'm using it in couple of places in Ionide

**Comment by MangelMaxime** [comment]
Ok, I will work on this issue and change the structure then
